"""INDEX.md: the chronicle's generated routing layer (ADR-047).

An agent reads this first. It says what matters now and where the canonical
record of each thing lives, and nothing more: pointers, not bodies. It is
compiled from authority, never read as authority, and carries no timestamp,
so identical records always give an identical index.
"""

from __future__ import annotations

import re

from . import analytics, layout
from .analytics import Report
from .model import Finding, Project

FILE = "INDEX.md"
# Rough token estimate: about four characters per token for English prose.
PREFERRED_TOKENS = 3000
WARNING_TOKENS = 5000
_LIST = 5          # items shown per list before "+N more"
_DECISIONS = 6
_READING = 8


def tokens(text: str) -> int:
    return (len(text) + 3) // 4


def _more(items: list[str], limit: int = _LIST) -> list[str]:
    shown = items[:limit]
    if len(items) > limit:
        shown.append(f"… and {len(items) - limit} more")
    return shown


def _excerpt(text: str, limit: int = 360) -> str:
    """The first meaningful lines of a narrative file, without its heading."""
    lines = [
        line.strip() for line in text.splitlines()
        if line.strip() and not line.startswith("#")
        and not line.startswith("Current implementation continuity")
    ]
    joined = " ".join(lines)
    return joined if len(joined) <= limit else joined[: limit - 1].rstrip() + "…"


def _section(text: str, heading: str) -> str:
    match = re.search(rf"(?ms)^## {re.escape(heading)}\s*\n(.*?)(?=^## |\Z)", text)
    return match.group(1) if match else ""


def _journal_headings(project: Project, root) -> list[str]:
    path = root / layout.AUTHORITY_DIR / "JOURNAL.md"
    if not path.is_file():
        return []
    return re.findall(r"(?m)^## (.+)$", path.read_text())


def view(project: Project, report: Report, root) -> dict[str, object]:
    """Everything the index says, selected from compiled state."""
    tasks = {t.id: t for t in project.tasks}
    current = project.phase(project.current_phase or "")
    blocker = report.main_blocker
    gate = report.next_gate
    operations = report.operations_metrics()
    focus_tasks = [*report.in_flight, *report.critical_path[:3]]
    if gate and gate["exitAuthority"]:
        focus_tasks.append(gate["exitAuthority"])
    if blocker and blocker["kind"] == "TASK":
        focus_tasks += [blocker["id"], blocker["blocking"]]
    focus_tasks = list(dict.fromkeys(t for t in focus_tasks if t in tasks))

    attention = [d for d in project.debts if d.needs_attention]
    attention.sort(key=lambda d: (
        {"REACHED": 0, "APPROACHING": 1}.get(d.trigger_state, 2), d.status != "OPEN", d.id,
    ))
    decisions: list[str] = []
    for task_id in focus_tasks:
        decisions += [d for d in tasks[task_id].decisions if d.startswith("ADR-")]
    for debt in attention:
        decisions += [r for r in debt.introduced_by if r.startswith("ADR-")]
    known = {d.id: d for d in project.decisions}
    decisions = [d for d in dict.fromkeys(decisions) if d in known][:_DECISIONS]

    active_operations = [t.id for t in project.operations_tasks if t.status == "WIP"]
    debt_counts = {s: sum(1 for d in project.debts if d.status == s)
                   for s in ("OPEN", "ACCEPTED", "SCHEDULED", "RESOLVED", "INVALIDATED")}
    return {
        "current": current,
        "blocker": blocker,
        "gate": gate,
        "focus": focus_tasks,
        "operations": operations,
        "activeOperations": active_operations,
        "unresolved": analytics.unresolved_failures(project),
        "attention": attention,
        "debtCounts": debt_counts,
        "triggerReached": sum(1 for d in project.debts if d.trigger_state == "REACHED" and not d.closed),
        "decisions": [known[d] for d in decisions],
        "journal": _journal_headings(project, root)[-3:][::-1],
    }


def render(project: Project, report: Report, root) -> str:
    v = view(project, report, root)
    tasks = {t.id: t for t in project.tasks}
    current, gate, blocker = v["current"], v["gate"], v["blocker"]
    progress = report.phase_progress.get(current.id) if current else None

    def task_line(task_id: str, note: str = "") -> str:
        task = tasks[task_id]
        extra = f" · {note}" if note else ""
        return f"- {task.id} · {task.status}{extra} — {task.title} → TASKS.md#{task.id}"

    lines = [
        "# Prokron project index",
        "",
        f"<!-- Generated by prokron {layout.version()} from the canonical chronicle. "
        "Do not edit: this file is overwritten on every compile and is never read "
        "as authority. When it disagrees with a record, the record wins. -->",
        "",
        "Read this first, then only the records it points to. Pointers use "
        "`file#anchor`; every file is in `.prokron/chronicle/`.",
        "",
        "## Current",
        "",
        f"- project: {project.name}",
        f"- phase: {current.id if current else 'none'}",
        f"- phase_status: {current.status if current else 'none'}",
        f"- phase_progress: {progress.done}/{progress.total}" if progress else "- phase_progress: none",
        f"- execution_task: {', '.join(report.in_flight) or 'none'}",
        f"- next_gate: {gate['exitAuthority'] if gate and gate['exitAuthority'] else 'none'}",
        f"- gates_not_ready: {', '.join(g['id'] for g in (gate or {}).get('gates', []) if not g['ready']) or 'none'}",
        f"- main_blocker: {blocker['id'] if blocker else 'none'}",
        f"- blocking: {blocker['blocking'] if blocker else 'none'}",
        f"- operations_affecting_execution: {', '.join(v['operations']['affectingExecution']) or 'none'}",
        f"- operations_active: {', '.join(v['activeOperations']) or 'none'}",
        f"- debt_attention: {', '.join(d.id for d in v['attention']) or 'none'}",
        f"- decisions_now: {', '.join(d.id for d in v['decisions']) or 'none'}",
        f"- unresolved_failures: {len(v['unresolved'])}",
    ]

    intent = _excerpt(project.intent)
    lines += ["", "## Intent", "", intent or "No intent recorded.", "", "→ INTENT.md"]

    lines += ["", "## Execution", ""]
    if current:
        lines.append(f"- phase: {current.id} {current.name} · {current.status} · "
                     f"{progress.done}/{progress.total} execution tasks → PHASES.md#{current.id}")
    else:
        lines.append("- phase: none active → PHASES.md")
    if report.in_flight:
        lines.append("- in flight:")
        lines += ["  " + task_line(t, "critical path" if t in report.critical_path else "")
                  for t in report.in_flight[:_LIST]]
    else:
        lines.append("- in flight: none")
    if report.critical_path:
        path = _more(report.critical_path)
        lines.append(f"- critical path: {' → '.join(path)}")
    if gate:
        authority = gate["exitAuthority"]
        if authority in tasks:
            lines.append(f"- next gate: {authority} · {tasks[authority].status} — exit authority for "
                         f"{gate['phase']} → TASKS.md#{authority}, ACCEPTANCE.md#{tasks[authority].contract}")
        for g in gate["gates"]:
            lines.append(f"- gate: {g['id']} · {g['status']}{'' if g['ready'] else ' · not ready'} → PHASES.md#{g['id']}")
    if blocker:
        where = f"TASKS.md#{blocker['id']}" if blocker["kind"] == "TASK" else f"PHASES.md#{blocker['id']}"
        label = " · project operations" if blocker["domain"] == "operations" else ""
        lines.append(f"- main blocker: {blocker['id']}{label} blocks {blocker['blocking']} "
                     f"({blocker['reason']}) → {where}")
    else:
        lines.append("- main blocker: none")
    failures = [f["task"] for f in report.execution_failures]
    if failures:
        lines.append(f"- execution failures: {', '.join(_more(failures))}")

    lines += ["", "## Operations", ""]
    ops = v["operations"]
    lines.append(f"- open: {ops['tasks']['open']} · active: {ops['tasks']['active']} · "
                 f"blocked: {ops['tasks']['blocked']} · events: {ops['events']['total']}")
    for task_id in v["activeOperations"][:_LIST]:
        lines.append("  " + task_line(task_id))
    for task_id, blockers in sorted(report.external_blockers.items())[:_LIST]:
        lines.append(f"- {task_id} waits on operations {', '.join(blockers)} → "
                     + ", ".join(f"TASKS.md#{b}" for b in blockers))
    if v["unresolved"]:
        lines.append(f"- unresolved failures: {', '.join(_more(v['unresolved'], 3))} → "
                     + ", ".join(f"TRACE.md#{e}" for e in v["unresolved"][:3]))

    lines += ["", "## Technical debt", ""]
    c = v["debtCounts"]
    lines.append(f"- open: {c['OPEN']} · accepted: {c['ACCEPTED']} · scheduled: {c['SCHEDULED']} · "
                 f"resolved: {c['RESOLVED']} · invalidated: {c['INVALIDATED']} · "
                 f"trigger reached: {v['triggerReached']}")
    for debt in v["attention"][:_LIST]:
        state = debt.trigger_state.lower().replace("_", " ")
        lines.append(f"- {debt.id} · {debt.status} · trigger {state} — {debt.title} → TECH_DEBT.md#{debt.id}")
    if len(v["attention"]) > _LIST:
        lines.append(f"- … and {len(v['attention']) - _LIST} more needing attention")

    lines += ["", "## Decisions that matter now", ""]
    if v["decisions"]:
        lines += [f"- {d.id} — {d.title} → ADR/{d.id}.md" for d in v["decisions"]]
    else:
        lines.append("- none linked to current work → ADR/README.md")

    handoff = _section(project.handoff, "Next action") or project.handoff
    lines += ["", "## Handoff", "", _excerpt(handoff, 300) or "No handoff recorded.", "", "→ HANDOFF.md"]

    lines += ["", "## Recent changes", ""]
    if v["journal"]:
        lines += [f"- {heading} → JOURNAL.md#{heading}" for heading in v["journal"]]
    else:
        lines.append("- none recorded → JOURNAL.md")

    reading: list[str] = []
    for task_id in v["focus"][:3]:
        reading.append(f"TASKS.md#{task_id}")
        if tasks[task_id].contract:
            reading.append(f"ACCEPTANCE.md#{tasks[task_id].contract}")
    reading += [f"TECH_DEBT.md#{d.id}" for d in v["attention"][:2]]
    reading += [f"ADR/{d.id}.md" for d in v["decisions"][:2]]
    reading.append("HANDOFF.md")
    reading = list(dict.fromkeys(reading))[:_READING]
    lines += ["", "## Suggested reading", ""]
    lines += [f"{i}. {ref}" for i, ref in enumerate(reading, 1)]
    lines += [
        "",
        "For a question, `prokron retrieve \"<question or id>\"` returns only the "
        "records it needs, each with its source.",
    ]
    # Whether CodeGraph is installed is a fact about this machine, not the
    # project, so the index says only how to reach it (ADR-049).
    focus = v["focus"][0] if v["focus"] else None
    lines += [
        "",
        "## Implementation intelligence",
        "",
        "Optional, and only after the records above have answered what matters: "
        "`prokron retrieve <task> --code` adds code structure from CodeGraph where it "
        "is installed; `prokron codegraph status` says whether it is.",
    ]
    if focus:
        lines.append(f"- suggested: `prokron retrieve {focus} --code`")
    return "\n".join(lines) + "\n"


def findings(project: Project, report: Report, root) -> list[Finding]:
    """Missing, stale, hand-edited, or oversized index."""
    path = root / layout.AUTHORITY_DIR / FILE
    fresh = render(project, report, root)
    found: list[Finding] = []
    if not path.is_file():
        found.append(Finding("warning", "index-missing", "INDEX.md has not been generated; run prokron compile", FILE))
    elif path.read_text() != fresh:
        found.append(Finding("warning", "index-stale",
                             "INDEX.md differs from the records; run prokron compile (edits to it are never kept)", FILE))
    size = tokens(fresh)
    if size > WARNING_TOKENS:
        found.append(Finding("warning", "index-too-large",
                             f"INDEX.md is about {size} tokens; the budget is {WARNING_TOKENS}", FILE))
    return found
