"""Markdown views of compiled state.

These replace the hand-maintained STATE.md and TASK_GRAPH.md. They carry no
fact that is not derived from `prokron/`, which is what makes the compiled
directory safe to delete: regenerating it loses nothing.

Narrative — risks, judgement, what to do next and why — belongs in the authored
HANDOFF.md. These files stay descriptive on purpose.
"""

from __future__ import annotations

from .analytics import Report
from .model import Project

HEADER = (
    "<!-- Generated by `prokron compile`. Do not edit. Edit `prokron/` instead. -->\n"
)


def readme() -> str:
    return (
        HEADER
        + """
# Compiled state

Every file in this directory is generated from the authored documents in
`prokron/`. Nothing here is authoritative and nothing here should be edited by
hand. Delete the directory and run `prokron compile` to rebuild it.

| File | What it holds |
| --- | --- |
| `project.json` | The whole compiled project, with provenance for every object. |
| `STATE.md` | Where the project stands right now. |
| `TASK_GRAPH.md` | Dependencies, ready work, and blockers. |
| `dashboard.html` | The same state as a browsable page. |
| `*.mmd` | Mermaid views: task graph, critical path, phases, gates, timelines. |
"""
    )


def state(project: Project, report: Report) -> str:
    metrics = report.metrics()
    lines = [HEADER, "# State", ""]
    lines.append(f"- Project: {project.name}")
    lines.append(f"- Current phase: {project.current_phase or 'none'}")
    lines.append(
        f"- Tasks: {metrics['taskCompletion']['done']} of "
        f"{metrics['taskCompletion']['total']} done"
    )
    lines.append(
        f"- Acceptance: {metrics['acceptanceCompletion']['done']} of "
        f"{metrics['acceptanceCompletion']['total']} criteria passing"
    )
    lines.append(
        f"- Validation: {metrics['validationCoverage']['done']} of "
        f"{metrics['validationCoverage']['total']} reviewed or verified"
    )
    lines.append(
        f"- Gates: {metrics['gateReadiness']['done']} of "
        f"{metrics['gateReadiness']['total']} green"
    )

    lines += ["", "## Phases", ""]
    for phase in project.phases:
        progress = report.phase_progress[phase.id]
        authority = f", exit authority {phase.exit_authority}" if phase.exit_authority else ""
        lines.append(
            f"- {phase.id} {phase.name}: {progress} tasks, {phase.status}{authority}"
        )

    lines += ["", "## Gates", ""]
    for gate in project.gates:
        lines.append(f"- {gate.id} {gate.name}: {gate.status}")
    if not project.gates:
        lines.append("- None recorded.")

    lines += ["", "## Work", ""]
    lines.append(f"- In flight: {', '.join(report.wip) or 'none'}")
    lines.append(f"- Ready: {', '.join(report.ready) or 'none'}")
    lines.append(f"- Blocked: {', '.join(report.blocked) or 'none'}")
    if report.critical_path:
        lines.append(f"- Critical path: {' → '.join(report.critical_path)}")

    lines += ["", "## Obstacles", ""]
    for obstacle in report.obstacles:
        lines.append(f"- {obstacle.type}: {obstacle.detail}")
    if not report.obstacles:
        lines.append("- None. Everything open is startable.")

    lines += [
        "",
        "## Narrative",
        "",
        "Risks, judgement, and the reason behind the next action are authored in",
        "`prokron/HANDOFF.md`. This file reports only what compiles.",
        "",
    ]
    return "\n".join(lines)


def task_graph(project: Project, report: Report) -> str:
    lines = [HEADER, "# Task graph", ""]
    by_status: dict[str, list[str]] = {}
    for task in project.tasks:
        by_status.setdefault(task.status, []).append(task.id)
    lines.append("## Summary")
    lines.append("")
    for status in ("WIP", "TODO", "BLOCKED", "DONE"):
        if status in by_status:
            lines.append(f"- {status}: {', '.join(by_status[status])}")
    lines.append(f"- Eligible now: {', '.join(report.ready) or 'none'}")
    lines.append(f"- Waiting: {', '.join(report.blocked) or 'none'}")

    lines += ["", "## Tasks", ""]
    for task in project.tasks:
        unlocks = report.downstream.get(task.id, [])
        eligible = "yes" if task.id in report.ready else "no"
        lines.append(f"- {task.id} [{task.status}] {task.title}")
        lines.append(f"  - phase: {task.phase}")
        lines.append(f"  - depends on: {', '.join(task.dependencies) or 'none'}")
        lines.append(f"  - unlocks: {', '.join(unlocks) or 'none'}")
        lines.append(f"  - eligible: {eligible}")
    return "\n".join(lines) + "\n"


def render_all(project: Project, report: Report) -> dict[str, str]:
    return {
        "README.md": readme(),
        "STATE.md": state(project, report),
        "TASK_GRAPH.md": task_graph(project, report),
    }
